"""Agregar campo profundidad a la tabla pared

Revision ID: 629cda41d611
Revises: 4334050a65d5
Create Date: 2024-11-25 19:05:16.777391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629cda41d611'
down_revision = '4334050a65d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pared', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profundidad', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pared', schema=None) as batch_op:
        batch_op.drop_column('profundidad')

    # ### end Alembic commands ###
