"""Initial migration

Revision ID: af9075e94a6f
Revises: 
Create Date: 2024-08-28 14:17:25.260888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af9075e94a6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor_material',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id_proveedor', 'id_material')
    )
    op.create_table('historial_mediciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechaHora', sa.DateTime(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('ancho', sa.Float(), nullable=False),
    sa.Column('costoTotal', sa.Float(), nullable=False),
    sa.Column('id_pared', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id'], ),
    sa.ForeignKeyConstraint(['id_pared'], ['pared.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('historialmediciones')
    op.drop_table('proveedormaterial')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('pared', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_proyecto', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_material', sa.Integer(), nullable=False))
        batch_op.drop_constraint('pared_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'material', ['id_material'], ['id'])
        batch_op.create_foreign_key(None, 'proyecto', ['id_proyecto'], ['id'])
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('contacto',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_constraint('proyecto_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('mail',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('contraseña',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('contraseña',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.alter_column('mail',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)

    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('proyecto_ibfk_1', 'usuario', ['id_usuario'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('contacto',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)

    with op.batch_alter_table('pared', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pared_ibfk_1', 'usuario', ['id_usuario'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('id_material')
        batch_op.drop_column('id_proyecto')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)

    op.create_tableif_not_exists('proveedormaterial',
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_material', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id'], name='proveedormaterial_ibfk_2', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], name='proveedormaterial_ibfk_1', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_proveedor', 'id_material'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_tableif_not_exists('historialmediciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fechaHora', mysql.DATETIME(), nullable=False),
    sa.Column('altura', mysql.FLOAT(), nullable=False),
    sa.Column('ancho', mysql.FLOAT(), nullable=False),
    sa.Column('costoTotal', mysql.FLOAT(), nullable=False),
    sa.Column('id_pared', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_material', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id'], name='historialmediciones_ibfk_2', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_pared'], ['pared.id'], name='historialmediciones_ibfk_1', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('historial_mediciones')
    op.drop_table('proveedor_material')
    # ### end Alembic commands ###
