"""Add contraseña_hash column to Usuario

Revision ID: f89608e06fe6
Revises: af9075e94a6f
Create Date: 2024-09-04 14:48:25.198793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f89608e06fe6'
down_revision = 'af9075e94a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    op.drop_table('proveedor_material')
    with op.batch_alter_table('historial_mediciones', schema=None) as batch_op:
        batch_op.drop_constraint('historial_mediciones_ibfk_1', type_='foreignkey')
        batch_op.drop_column('id_material')

    with op.batch_alter_table('pared', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altura', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ancho', sa.Float(), nullable=False))

    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('contraseña_hash')

    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('pared', schema=None) as batch_op:
        batch_op.drop_column('ancho')
        batch_op.drop_column('altura')

    with op.batch_alter_table('historial_mediciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_material', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('historial_mediciones_ibfk_1', 'material', ['id_material'], ['id'])

    op.create_table('proveedor_material',
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_material', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id'], name='proveedor_material_ibfk_1'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], name='proveedor_material_ibfk_2'),
    sa.PrimaryKeyConstraint('id_proveedor', 'id_material'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contacto', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
